services:
  app:
    build: ./services/app
    container_name: app-services
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
  users:
    build: ./services/users
    container_name: user-services
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - MONGODB=${MONGODB}
  orchestrator:
    build: ./orchestrator-graphql
    container_name: orchestrator
    ports:
      - "4000:4000"
    environment:
      - REDISLAB_URL=${REDISLAB_URL}
      - APP_FIRST_SERVER_URL=${APP_FIRST_SERVER_URL}
      - USER_SECOND_SERVER_URL=${USER_SECOND_SERVER_URL}